### DISCUSSION TITLE
Repository context for code completion

### DISCUSSION THREAD

**Discussion by xbraindance** [TabbyML/tabby#1218] [Q&A] [answered]
I've created and modified the config.toml to point to local folder were the I have my repositories but I'm getting this error message when running the scheduler even though both folders exist:

# Index three repositories' source code as additional context for code completion.

[[repositories]]
name = "ML"
git_url = "/Users/click/ML"

[[repositories]]
name = "TabbyCodebaseCompletionDB"
git_url = "/Users/click/TabbyCodebaseCompletionDB"

–––––––––––––––––––––––––––––––––––––––

Syncing repositories...
Cloning into '/Users/click/.tabby/repositories/_Users_click_ML'...
warning: You appear to have cloned an empty repository.
done.
fatal: repository '/Users/click/TabbyCodebaseCompletionDB' does not exist
2024-01-16T20:36:33.228895Z ERROR tabby_scheduler: crates/tabby-scheduler/src/lib.rs:19: Failed to sync repositories, err: 'Failed to pull remote '/Users/click/TabbyCodebaseCompletionDB'. Consider remove dir '/Users/click/.tabby/repositories/_Users_click_TabbyCodebaseCompletionDB' and retry'
Indexing repositories...

**Comment by wsxiaoys** [comment, marked as answer]
Hi, as demonstrated in https://tabby.tabbyml.com/docs/configuration , local directory requires prefixing the path with `file://`

So it should be

```toml
[[repositories]]
name = "ML"
git_url = "file:///Users/click/ML"

[[repositories]]
name = "TabbyCodebaseCompletionDB"
git_url = "file:///Users/click/TabbyCodebaseCompletionDB"
```
