### DISCUSSION TITLE
Reindexing every hour?

### DISCUSSION THREAD

**Discussion by Geremia** [TabbyML/tabby#2288] [Q&A]
Every hour, `tabby` `scheduler` spends about 20 min. re-indexing all 56 of my imported GitHub repos. There's no need to constantly keep doing this. Is there a way to turn off indexing?

**Comment by wsxiaoys** [comment]
Indexing is incremental and it shouldn't cost that long if nothing got changed.

Please provide more information (e.g version, config, logs) to help identify the problem. Thank you!

**Comment by Geremia** [comment]
@wsxiaoys  I'm using `--no-webserver` now with all my GitHub repos in `~/.tabby/config.toml`, and I'm not getting the 20 min. reindexing issue every hour anymore.

**Reply by wsxiaoys** [reply]
would you mind sharing your config.toml (probably in a gist)? happy to help debug on its performance

**Reply by Geremia** [reply]
@wsxiaoys 

<details><summary>~/.tabby/config.toml</summary>
<p>

```toml
[[repositories]]
name = "tabby"
git_url = "https://github.com/Geremia/tabby"

[[repositories]]
name = "LibgenBulkUpload"
git_url = "https://github.com/Geremia/LibgenBulkUpload"

[[repositories]]
name = "divinum-officium"
git_url = "https://github.com/Geremia/divinum-officium"

[[repositories]]
name = "Her-Triumph"
git_url = "https://github.com/Geremia/Her-Triumph"

[[repositories]]
name = "IsoGrego"
git_url = "https://github.com/Geremia/IsoGrego"

[[repositories]]
name = "binsim"
git_url = "https://github.com/Geremia/binsim"

[[repositories]]
name = "AquinasOperaOmnia"
git_url = "https://github.com/Geremia/AquinasOperaOmnia"

[[repositories]]
name = "documentation"
git_url = "https://github.com/Geremia/documentation"

[[repositories]]
name = "WeberSim"
git_url = "https://github.com/Geremia/WeberSim"

[[repositories]]
name = "LatinInflector"
git_url = "https://github.com/Geremia/LatinInflector"

[[repositories]]
name = "chapterize"
git_url = "https://github.com/Geremia/chapterize"

[[repositories]]
name = "Veni-Creator-Palestrina-with-Gregorian-verses-"
git_url = "https://github.com/Geremia/Veni-Creator-Palestrina-with-Gregorian-verses-"

[[repositories]]
name = "euler_all_undos"
git_url = "https://github.com/Geremia/euler_all_undos"

[[repositories]]
name = "mediawiki"
git_url = "https://github.com/Geremia/mediawiki"

[[repositories]]
name = "21lessons-book"
git_url = "https://github.com/Geremia/21lessons-book"

[[repositories]]
name = "merge-subs"
git_url = "https://github.com/Geremia/merge-subs"

[[repositories]]
name = "relscale"
git_url = "https://github.com/Geremia/relscale"

[[repositories]]
name = "mmyy_slackbuilds"
git_url = "https://github.com/Geremia/mmyy_slackbuilds"

[[repositories]]
name = "OpenNMT-py"
git_url = "https://github.com/Geremia/OpenNMT-py"

[[repositories]]
name = "MondotimesScraper"
git_url = "https://github.com/Geremia/MondotimesScraper"

[[repositories]]
name = "lnbook"
git_url = "https://github.com/Geremia/lnbook"

[[repositories]]
name = "bips"
git_url = "https://github.com/Geremia/bips"

[[repositories]]
name = "RichTextUnicode"
git_url = "https://github.com/Geremia/RichTextUnicode"

[[repositories]]
name = "map2gpx"
git_url = "https://github.com/Geremia/map2gpx"

[[repositories]]
name = "2020_benfords"
git_url = "https://github.com/Geremia/2020_benfords"

[[repositories]]
name = "benford_py"
git_url = "https://github.com/Geremia/benford_py"

[[repositories]]
name = "jgabc"
git_url = "https://github.com/Geremia/jgabc"

[[repositories]]
name = "sbopkg"
git_url = "https://github.com/Geremia/sbopkg"

[[repositories]]
name = "youtube-dl"
git_url = "https://github.com/Geremia/youtube-dl"

[[repositories]]
name = "open-search-generator"
git_url = "https://github.com/Geremia/open-search-generator"

[[repositories]]
name = "FizzBuzz"
git_url = "https://github.com/Geremia/FizzBuzz"

[[repositories]]
name = "scripts"
git_url = "https://github.com/Geremia/scripts"

[[repositories]]
name = "indexmeister"
git_url = "https://github.com/Geremia/indexmeister"

[[repositories]]
name = "groupexplorer"
git_url = "https://github.com/Geremia/groupexplorer"

[[repositories]]
name = "calibre"
git_url = "https://github.com/Geremia/calibre"

[[repositories]]
name = "openMVG"
git_url = "https://github.com/Geremia/openMVG"

[[repositories]]
name = "google-books-downloader"
git_url = "https://github.com/Geremia/google-books-downloader"

[[repositories]]
name = "pitch-ios-public"
git_url = "https://github.com/Geremia/pitch-ios-public"

[[repositories]]
name = "Weather"
git_url = "https://github.com/Geremia/Weather"

[[repositories]]
name = "Dijkstra"
git_url = "https://github.com/Geremia/Dijkstra"

[[repositories]]
name = "BitcoinTradeCalculator"
git_url = "https://github.com/Geremia/BitcoinTradeCalculator"

[[repositories]]
name = "FancyClock"
git_url = "https://github.com/Geremia/FancyClock"

[[repositories]]
name = "LatinDictionary"
git_url = "https://github.com/Geremia/LatinDictionary"

[[repositories]]
name = "Shingle"
git_url = "https://github.com/Geremia/Shingle"

[[repositories]]
name = "pkp-lib"
git_url = "https://github.com/Geremia/pkp-lib"

[[repositories]]
name = "Antidote"
git_url = "https://github.com/Geremia/Antidote"

[[repositories]]
name = "licut"
git_url = "https://github.com/Geremia/licut"

[[repositories]]
name = "libblkmaker"
git_url = "https://github.com/Geremia/libblkmaker"

[[repositories]]
name = "my_slackbuilds"
git_url = "https://github.com/Geremia/my_slackbuilds"

[[repositories]]
name = "btrbk-SlackBuild"
git_url = "https://github.com/Geremia/btrbk-SlackBuild"

[[repositories]]
name = "STDNBR2LCC"
git_url = "https://github.com/Geremia/STDNBR2LCC"

[[repositories]]
name = "elements"
git_url = "https://github.com/Geremia/elements"

[[repositories]]
name = "git"
git_url = "https://github.com/Geremia/git"

[[repositories]]
name = "botcoin"
git_url = "https://github.com/Geremia/botcoin"

[[repositories]]
name = "satfactor"
git_url = "https://github.com/Geremia/satfactor"

[[repositories]]
name = "optimap"
git_url = "https://github.com/Geremia/optimap"
```

</p>
</details> 

<details><summary>~/.tabby-client/agent/config.toml</summary>
<p>

```toml
## Tabby agent configuration file

## Online documentation: https://tabby.tabbyml.com/docs/extensions/configurations
## You can uncomment and edit the values below to change the default settings.
## Configurations in this file have lower priority than the IDE settings.

## Server
## You can set the server endpoint here and an optional authentication token if required.
[server]
endpoint = "http://localhost:8080" # http or https URL
token = "auth_61203341ab1d48e9a5c9f8fa57913036" # if token is set, request header Authorization = "Bearer $token" will be added automatically

## You can add custom request headers.
# [server.requestHeaders]
# Header1 = "Value1" # list your custom headers here
# Header2 = "Value2" # values can be strings, numbers or booleans

## Logs
## You can set the log level here. The log file is located at ~/.tabby-client/agent/logs/.
[logs]
level = "debug" # "silent" or "error" or "debug"

## Anonymous usage tracking
## Tabby collects anonymous usage data and sends it to the Tabby team to help improve our products.
## Your code, generated completions, or any sensitive information is never tracked or sent.
## For more details on data collection, see https://tabby.tabbyml.com/docs/extensions/configurations#usage-collection
## Your contribution is greatly appreciated. However, if you prefer not to participate, you can disable anonymous usage tracking here.
# [anonymousUsageTracking]
# disable = false # set to true to disable
```

</p>
</details> 

I think the issue was a conflict between the repos listed in `~/.tabby/config.toml` and the repos added in the webserver; [supposedly they're mutually exclusive](https://github.com/TabbyML/tabby/issues/1753#issuecomment-2031243838). `--no-webserver` seems to help it use only the repos listed in `~/.tabby/config.toml`.
Previously, the webserver (I think it was) completely deleted all the repos the `scheduler --now` put in the repos folder. (I think… I wish I could reproduce it. I re-enabled the webserver now, and it seems to be working; jobs are <1 sec now.)
