### DISCUSSION TITLE
Embedding always shows unreachable in the Systems tab

### DISCUSSION THREAD

**Discussion by realhackcraft** [TabbyML/tabby#3724] [Q&A]
<img width="589" alt="Screenshot 2025-01-18 at 10 56 54" src="https://github.com/user-attachments/assets/bea20aee-d41f-42ad-86a7-42fdda15f1b8" />

I am able to run the model, but the embedding keeps showing as unreachable.

Why is that?

**Comment by Cfomodz** [comment]
The embedding model fails when using local configuration. **Use HTTP endpoint instead**.

### 1. Start llama-server manually
```bash
llama-server --model /path/to/nomic-embed-text.gguf --port 30887
```

### 2. Update `~/.tabby/config.toml`
```toml
[model.completion.local]
model_id = "Qwen2.5-Coder-3B"

[model.chat.local]
model_id = "Qwen2.5-Coder-1.5B-Instruct"

[model.embedding.http]
kind = "llama.cpp/embedding"
model_name = "Nomic-Embed-Text"
api_endpoint = "http://127.0.0.1:30887"
```

### 3. Restart Tabby
```bash
tabby serve --model Qwen2.5-Coder-3B --device cuda
```
