### DISCUSSION TITLE
Would the tabby API work with services such as LibreChat/Open WebUI

### DISCUSSION THREAD

**Discussion by SoCuul** [TabbyML/tabby#3843] [Q&A]
If I'm understanding it correctly it seems like tabby is hosting the model and providing an API endpoint which can be accessed to interact with the model. Can this be integrated into a web ui such as LibreChat/Open Web UI or would I have to host the model more than once.

**Comment by Cfomodz** [comment]
**Yes, Tabby works with LibreChat and Open WebUI without hosting the model multiple times.** Tabby provides an OpenAI-compatible API endpoint that both platforms support.

Run Tabby once:
```bash
docker run -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model StarCoder-1B --device cuda --chat-model Qwen2-1.5B-Instruct
```

### LibreChat Integration

Add to `librechat.yaml`:
```yaml
endpoints:
  custom:
    - name: "Tabby"
      apiKey: "your-tabby-api-key"
      baseURL: "http://localhost:8080/v1"
      models:
        default: ["StarCoder-1B"]
```

### Open WebUI Integration

1. Go to **Admin Settings** → **Connections** → **OpenAI**
2. Add connection:
   - **API URL**: `http://localhost:8080/v1`
   - **API Key**: Your Tabby API key

```
Tabby Server (localhost:8080)
         ↓ OpenAI-compatible API
    ┌────┴────┐
    ↓         ↓
LibreChat   Open WebUI
```

**One model instance, multiple clients.**
