### ISSUE TITLE
docker-compose multi-gpu example

### ISSUE THREAD

**Issue by PeterTucker** [TabbyML/tabby#1013]
Can anyone give an example on how to get TabbyML working with two GPUs?

I have two 3060s. This is what I have so far, but I'm not sure if TabbyML is actually using both GPUs.

```
version: '3.5'

services:
  tabby:
    restart: always
    image: tabbyml/tabby:0.6.0
    command: serve --model TabbyML/StarCoder-3B  --chat-model TabbyML/WizardCoder-3B --device cuda
    #command: serve --model TabbyML/StarCoder-3B --device cuda
    volumes:
      - "./data:/data"
    ports:
      - 8080:8080
    environment:
      - CUDA_VISIBLE_DEVICES=0,1
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```

**Comment by wsxiaoys** [comment]
Since we don't do tensor parallelism at the moment, the only way to utilize multiple gpu is separate the workload into different process / different cuda devices.

In this particular case, you might:
1. start `serve --model TabbyML/StarCoder-3B --device cuda` on two container process.
2. Each container process has visibility of single cuda device.

**Comment by PeterTucker** [comment]
@wsxiaoys Any chance I could get a docker-compose example? Not sure how that would work if both containers are using port 8080

**Comment by PeterTucker** [comment]
Just separating the models into different containers to use each GPU seems to work.  I was hoping for a single model to use two GPUs, but that does not seem possible.

For anyone looking for a multi-gpu setup, here is the docker-compose setup:
```
version: '3.8'

services:
  tabby1:
    restart: always
    image: tabbyml/tabby:0.6.0
    command: serve --model TabbyML/StarCoder-7B --device cuda
    volumes:
      - ./data:/data
    ports:
      - 8080:8080
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  tabby2:
    restart: always
    image: tabbyml/tabby:0.6.0
    command: serve  --chat-model TabbyML/WizardCoder-3B --device cuda
    volumes:
      - ./data:/data
    ports:
      - 8081:8080
    environment:
      - CUDA_VISIBLE_DEVICES=1
      - NVIDIA_VISIBLE_DEVICES=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
