### ISSUE TITLE
CUDA error 711 at /root/workspace/crates/llama-cpp-bindings/llama.cpp/ggml-cuda.cu:6826: peer mapping resources exhausted

### ISSUE THREAD

**Issue by QIN2DIM** [TabbyML/tabby#1162]
**Describe the bug**

Docker Compose, CUDA error 711 at /root/workspace/crates/llama-cpp-bindings/llama.cpp/ggml-cuda.cu:6826: peer mapping resources exhausted

![bug](https://github.com/TabbyML/tabby/assets/62018067/8a6f823b-3349-4518-a5a8-87a1caf6815c)

**Information about your version**

```sh
tabbyml/tabby:latest    23bdb48b7956   2 weeks ago     
```

**Information about your GPU**

![cuda](https://github.com/TabbyML/tabby/assets/62018067/6b0ccba1-f3fc-4e73-a09f-1e2a34a81842)

**Additional context**
```yaml
version: '3.5'

services:
  tabby:
    restart: always
    image: tabbyml/tabby
    command: serve --model TabbyML/DeepseekCoder-6.7B --device cuda
    volumes:
      - "$HOME/.tabby:/data"
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      HTTPS_PROXY: http://192.168.1.180:2081
      HTTP_PROXY: http://192.168.1.180:2081
    ports:
      - 9999:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 9 # Setting it to 'all' or 10 will cause an error, otherwise everything will be normal.
              capabilities: [gpu]
```
