### ISSUE TITLE
OpenAI compatible API

### ISSUE THREAD

**Issue by l1onsun** [TabbyML/tabby#1766]
I have just deployed `tabby` with `DeepSeekCoder-6.7B` on my home server, and I'm really pleased with the results! Thank you so much for creating such a great open-source product!!

The problem i encountered - I want also to use the deployed model for other tasks, like ordinary chat.  I found that i can do it thought `/v1beta/chat_completions` API, but the response seems to be incompatible with OpenAI format, which is used by many tools.

Are there any ways to reuse tabby deployed model?

**Comment by wsxiaoys** [comment]
> I found that i can do it thought /v1beta/chat_completions API, but the response seems to be incompatible with OpenAI format, which is used by many tools.

Could you share the error message related to this? The endpoint /v1beta/chat/completions is designed to be compatible with the OAI format (we even use the OAI client library to interact with it). I would be happy to fix it if we could reproduce the issue.

**Comment by l1onsun** [comment]
Hm, i thought it incompatible. I used `aichat`, maybe i configured it wrong. My aichat config is:
```yaml
model: localai
clients:
- type: localai
  api_base: http://localhost:8080/v1beta
  models:
  - name: deepseek-coder
    max_input_tokens: 16384
```
And i got this error
```
Failed to get answer

Caused by:
    0: error decoding response body: EOF while parsing a value at line 1 column 0
    1: EOF while parsing a value at line 1 column 0
```
