### ISSUE TITLE
Local setup using Conda

### ISSUE THREAD

**Issue by nopperl** [TabbyML/tabby#2057]
It might make sense to add the option of using [Conda](https://docs.conda.io/en/latest/) to setup the local dev environment. It should make it easier for users as it's cross-platform and doesn't require root access.
To save people who want to do this the hassle of finding all the packages, here's the `environment.yaml` I used:

```yaml
name: tabby
channels:
  - conda-forge
  - defaults
  - nvidia/label/cuda-11.8.0
dependencies:
  - cmake>=3.18
  - compilers
  - cuda
  - git
  - gxx=11
  - libopenblas
  - openssl
  - pip
  - protobuf
  - python
  - rust
  - sysroot_linux-64>=2.17
```

(The `cuda` package can be removed if CUDA support is not required.)

The Conda env can then be created and activated using:

    conda create -f environment.yaml
    conda activate tabby

Note: the following env vars need to be set when building tabby:

```
OPENSSL_INCLUDE_DIR=$CONDA_PREFIX/include/openssl
OPENSSL_LIB_DIR=$CONDA_PREFIX/lib
LD_LIBRARY_PATH=$CONDA_PREFIX/lib/stubs:$CONDA_PREFIX/lib
LIBRARY_PATH=$CONDA_PREFIX/lib/stubs:$CONDA_PREFIX/lib
```

---
Please reply with a 👍 if you want this feature.
