### ISSUE TITLE
I tried the docker image without GPU

### ISSUE THREAD

**Issue by Zibri** [TabbyML/tabby#2082]
$ docker run -it \
  -p 8080:8080 -v $HOME/.tabby:/data \
  tabbyml/tabby \
  serve --model TabbyML/StarCoder-1B --device **cpu** 
Unable to find image 'tabbyml/tabby:latest' locally
latest: Pulling from tabbyml/tabby
aece8493d397: Pull complete 
976b13f9ef1a: Pull complete 
b63c65d3acaa: Pull complete 
4dda4739d007: Pull complete 
197843862cd5: Pull complete 
cf87cabd72e2: Pull complete 
7908cc89184b: Pull complete 
125997f82033: Pull complete 
675adc119131: Pull complete 
9591dddbc5be: Pull complete 
6ff2dc56b183: Pull complete 
e024c0ac0e95: Pull complete 
21d54a35fb7a: Pull complete 
Digest: sha256:b3f436d189882f34811908f1cac15bc7c3a1e72d522468b88a0ec497379b4bf2
Status: Downloaded newer image for tabbyml/tabby:latest
/opt/tabby/bin/tabby: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by wsxiaoys** [comment]
To run it on CPU, use `tabby-cpu` binary. See https://tabby.tabbyml.com/docs/installation/docker/ for references.

**Comment by bersace** [comment]
I'm using tabby-cpu:

``` yaml
---
services:
  tabby:
    container_name: tabby
    restart: always
    image: tabbyml/tabby
    entrypoint: /opt/tabby/bin/tabby-cpu
    command: serve --model StarCoder-1B
    volumes:
      - /home/bersace/.local/tabby:/data
```

And still hit this issue:

```
tabby  | 2024-07-12T13:38:33.933326Z  WARN llama_cpp_server::supervisor: crates/llama-cpp-server/src/supervisor.rs:99: llama-server <embedding> exited with status code 127
tabby  | 2024-07-12T13:38:33.933340Z  WARN llama_cpp_server::supervisor: crates/llama-cpp-server/src/supervisor.rs:111: <embedding>: /opt/tabby/bin/llama-server: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
```

It's properly running tabby-cpu according to ps. Seems like llama-server is not executed for CPU.

``` console
root@faaf3f6a1924:/# tabby-cpu --version
tabby 0.13.1
```

Regards,

**Comment by b-reich** [comment]
```yaml
services:
  tabby:
    restart: always
    image: tabbyml/tabby
    entrypoint: /opt/tabby/bin/tabby-cpu
    command: serve --model StarCoder-1B --chat-model Qwen2-1.5B-Instruct
    volumes:
      - ".data/tabby:/data"
    ports:
      - 8080:8080
```
which is document here https://tabby.tabbyml.com/docs/quick-start/installation/docker-compose/ wont work
