### ISSUE TITLE
ollama http api support

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#2176]
**Please describe the feature you want**

Following the recent refactoring of the HttpBackend, we now have the capability to support the Ollama HTTP API:
- [ ] Completion. For instance, see: https://github.com/TabbyML/tabby/blob/main/crates/http-api-bindings/src/completion/llama.rs
- [ ] Embedding. For example, refer to: https://github.com/TabbyML/tabby/blob/main/crates/http-api-bindings/src/embedding/llama.rs

For chat completion, as it is compatible with the OpenAI chat, there is no necessity to reimplement this feature.

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by SpeedCrash100** [comment]
Hi there,

I wanted to suggest that you consider implementing a new Ollama connector instead of using a generic HTTP API connector. There are a few reasons why I believe this would be a better solution:

1.  Someone(me of course :D) will request to ask ollama to try pull(aka download) model if it doesn't exists, a generic http-api has no reasons to have such an option.
2. Rust crate availability: There is a readily available `ollama-rs` crate that we can use to interact with the Ollama API.
3. Support for async streams: The `ollama-rs` crate supports async streams, which means that it can be easily integrated with `tabby-inference` with minimal transformations. 

Overall, I think the http api connector tries to be far too generic. Narrowing its scope will make naming clearer and allow Ollama specific features to be implemented without adding unused fields. This is just a suggestion. I don't mind if you or anyone else implements it the way you want.

**Comment by SpeedCrash100** [comment]
I have created kinda "Proof of concept" implementation [here](https://github.com/Deka-AI-Coding/tabby/tree/ollama). I don't know what is embedding and how to check it. As for chat completions, they seems working with the config below, completions needs fixes but generates code as well:

```toml
[model.chat.ollama]
url = "http://localhost"
port = 11434
model_name = "llama3"


[model.completion.ollama]
url = "http://localhost"
port = 11434
model_name = "starcoder2"
prompt_template = "<fim_prefix>{prefix}<fim_suffix>{suffix}<fim_middle>"

[model.embedding.ollama]
url = "http://localhost"
port = 11434
model_name = "llama3"    # I'm not sure what is embedding and what is needed for it.

```

BTW, why [`CompletionStream::generate`](https://github.com/TabbyML/tabby/blob/0d63bea0b185bff282b96b0a8a3999cf56b80f72/crates/tabby-inference/src/completion.rs#L18C75-L18C84) does not return `Result<BoxStream<String>>` like any other interfaces in crate? This will cause panics in future.
