### ISSUE TITLE
docker compose v2 

### ISSUE THREAD

**Issue by Allesanddro** [TabbyML/tabby#232]
On docker compose v2 the provided yml file is not supported.

This would  be the "correct" compose file for v2

```
version: '3.5'
services:
  tabby:
    restart: always
    image: tabbyml/tabby
    command: serve --model TabbyML/SantaCoder-1B --device cuda
    volumes:
      - "$HOME/.tabby:/data"
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
