### ISSUE TITLE
C# support

### ISSUE THREAD

**Issue by Suriman** [TabbyML/tabby#239]
Will Tabby supports C#?

**Comment by wolf-li** [comment]
You can train the model or use the exist model to replace the 

> Will Tabby supports C#?

You can chenge the model using [Codegen2-4B](https://huggingface.co/TabbyML/Codegen2-4B) . This orginal model support c, c++, c-sharp, dart, go, java, javascript, kotlin, lua, php, python, ruby, rust, scala, shell, sql, swift, typescript, vue language. But I haven't to test this.

**Comment by joesdu** [comment]
> You can train the model or use the exist model to replace the
> 
> > Will Tabby supports C#?
> 
> You can chenge the model using [Codegen2-4B](https://huggingface.co/TabbyML/Codegen2-4B) . This orginal model support c, c++, c-sharp, dart, go, java, javascript, kotlin, lua, php, python, ruby, rust, scala, shell, sql, swift, typescript, vue language. But I haven't to test this. I try Codegen2-4B model. The effect of this model is mediocre. Suggest to use [WizardLM](https://huggingface.co/WizardLM)/[WizardCoder-15B-V1.0](https://huggingface.co/WizardLM/WizardCoder-15B-V1.0)

I see that the model in the official docker-composite file is not the command for the model I downloaded. How should I say that the file path is mapped into the container and modify the model name? Can you give me an example? My model is [Codegen2-7B](https://huggingface.co/Salesforce/codegen2-7B)

```yaml
version: '3.5'
services:
  tabby:
    restart: always
    image: tabbyml/tabby
    command: serve --model TabbyML/SantaCoder-1B --device cuda
    volumes:
      - "$HOME/.tabby:/data"
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
