### ISSUE TITLE
Request: Deepseek Coder V2 model

### ISSUE THREAD

**Issue by kba-tmn3** [TabbyML/tabby#2451]
I would like to use bartowski/DeepSeek-Coder-V2-Lite-Instruct-GGUF, but I have a problem with launching it properly with TabbyML.

I forked a registry and start downloading it correctly, but after downloading tabby is not responding anyway, I tried to wait, but it doesn't work and logs are empty at all.

**Additional context**
Registry https://github.com/kba-tmn3/registry-tabby
Command line 
```
docker run -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model kba-tmn3/DeepseekCoder-V2 --device cuda
```
Source https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
GGUF https://huggingface.co/bartowski/DeepSeek-Coder-V2-Lite-Instruct-GGUF
Accurancy of the model
![Comparison with other models](https://github.com/TabbyML/tabby/assets/157360605/819c7c7e-de2e-4e42-a05b-3eca98724027)

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Thanks for the feature request.

> I forked a registry and start downloading it correctly, but after downloading tabby is not responding anyway, I tried to wait, but it doesn't work and logs are empty at all.

Could you turn on `RUST_LOG=debug RUST_BACKTRACE=1` in your docker environment and share its output?

**Comment by kba-tmn3** [comment]
> Could you turn on `RUST_LOG=debug RUST_BACKTRACE=1` in your docker environment and share its output?

Sorry, but it can not log anything, I added environment variables and it's empty at all, hangs as running status and nothing working.

Command line ```RUST_LOG=debug RUST_BACKTRACE=1 docker run -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model kba-tmn3/DeepseekCoder-V2 --device cuda```

It utilize 98,42% CPU (%) in docker desktop and task manager's hardware monitor looks like this

![image](https://github.com/TabbyML/tabby/assets/157360605/33e7c9eb-b781-4d29-a77c-190dcaa0a436)

**Comment by wsxiaoys** [comment]
to pass environment flag to docker, you need to do something like `-e RUST_BACKTRACE=1` - could you try again?

It's very likely the stuck is caused by model loading / computation, though

**Comment by kba-tmn3** [comment]
I guess it because of version of llama.cpp tabby using 

model using this for quantization https://github.com/ggerganov/llama.cpp/releases/tag/b3166

Logs 
[logs.txt](https://github.com/user-attachments/files/15922827/logs.txt)

**Comment by kba-tmn3** [comment]
Sorry for external links, but I found some people stuck with the problem on russian forum named Habr:
 https://habr.com/ru/news/822503/comments/#:~:text=llama.cpp%20unknown%20model%20architecture%3A%20%27deepseek2%27

I attach the link with text of error they stuck (did i receive the same message? idk)

**Comment by wsxiaoys** [comment]
Right - this means the support of DeepseekCoder v2 in llama.cpp is only added very recently, will try include it in the upcoming 0.13 release

**Comment by Mizzlr** [comment]
Just for added context, ollama just started support for deepseekcoder v2. See https://github.com/ollama/ollama/releases/tag/v0.1.45 

I was wondering the same from tabby. 

Thanks again, looking forward to release 0.13

**Comment by wsxiaoys** [comment]
For context - you can actually connect tabby to ollama by using config.toml based model configuration.

See https://tabby.tabbyml.com/docs/administration/model/#ollama for example

**Comment by f6ra07nk14** [comment]
> For context - you can actually connect tabby to ollama by using config.toml based model configuration: https://tabby.tabbyml.com/docs/administration/model/#ollama

Can you give an example shown how to create tabby server with model configuration by `docker`.

**Comment by LLukas22** [comment]
@f6ra07nk14 

Here is a simple example im currently using to run tabby with an `ollama` server as it's llm backend to use `deepseek-coder-v1` for code completions and `deepseek-coder-v2` as a chat model.

**config.toml**
```toml
[model.completion.http]
kind = "ollama/completion"
model_name = "deepseek-coder"
api_endpoint = "http://ollama:11434" # Insert your URL here
prompt_template = "<｜fim▁begin｜>{prefix}<｜fim▁hole｜>{suffix}<｜fim▁end｜>"

[model.chat.http]
kind = "ollama/chat"
model_name = "deepseek-coder-v2"
api_endpoint = "http://ollama:11434" # Insert your URL here
```

**docker-compose.yml**

```yml
version: '3.5'
services:
  tabby:
    restart: always
    image: ghcr.io/tabbyml/tabby:0.13.0-rc.3
    command: serve 
    volumes:
      - "./tabby:/data"
      - "./config.toml:/data/config.toml"
    ports:
      - 8080:8080
```

Basically to use the `config.toml` you have to mount it into the `/data/` directory of the container. Contrary to the documentation you also have to provide a `model_name` in the `[model.completion.http]` for the completion model to work.
