### ISSUE TITLE
Indexing so slow?

### ISSUE THREAD

**Issue by brian316** [TabbyML/tabby#2494]
**Describe the bug**
Indexing takes 1+ hour. I am using open ai `Text-embedding-3-small`  for my embeddings. Also the logs are so dry I don't get any useful information. is there any way i can turn on better logging i don't see anything in the docs.

**Information about your version**
Version 0.12.0

**Information about your GPU**
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2070 ...  WDDM  |   00000000:2D:00.0  On |                  N/A |
| 15%   55C    P0             46W /  215W |    1490MiB /   8192MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```
**Additional context**
My system:
- 64gb ram
- Ryzen 7 3700x 8-Core
- rtx 2070 super
- windows 11

My docker-compose file
```yaml
version: '3.5'

services:
  tabby:
    restart: always
    image: tabbyml/tabby
    command: serve --device cuda
    environment:
      - TABBY_DISABLE_USAGE_COLLECTION=1
    volumes:
      - "C:/Users/brian/.tabby:/data"
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

the only logs i get are not that useful

![image](https://github.com/TabbyML/tabby/assets/3878246/dd8a9959-367a-4c08-9360-65833f430b1a)

![image](https://github.com/TabbyML/tabby/assets/3878246/24dd2085-0667-4f31-8773-e6e9e292fdb6)

Open AI dashboard shows some usage but lots of downtime
![image](https://github.com/TabbyML/tabby/assets/3878246/8bc61f63-ddfa-4969-b721-b97bb1062bc9)

Running on windows 11. shows low to no usage
![image](https://github.com/TabbyML/tabby/assets/3878246/a56ee083-f248-4412-a9e2-d9a8c702b704)
