### ISSUE TITLE
GPU not working on 0.13.0, runs on CPU

### ISSUE THREAD

**Issue by PeterTucker** [TabbyML/tabby#2551]
**Describe the bug**
TabbyML 0.13.0 doesn't seem to use my 3060 GPU. When I trigger code completion, I see the CPU run at 100%. I'm using WSL2.

docker-compose.yaml:
```
services:

  tabby:
    restart: always
    image: tabbyml/tabby:0.13.0
    command: serve --model TabbyML/DeepseekCoder-1.3B --device cuda #--chat-model Qwen2-1.5B-Instruct 
    volumes:
       - ./data:/data
    ports:
      - 8080:8080
    environment:
     - CUDA_VISIBLE_DEVICES=1
     - NVIDIA_VISIBLE_DEVICES=1
     - RUST_BACKTRACE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

On another docker container it seems to run nvidia-smi just fine:
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.52.01              Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        On  |   00000000:01:00.0  On |                  N/A |
|  0%   51C    P8             17W /  170W |     728MiB /  12288MiB |     16%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
nvidia-smi-test-1  |
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Information about your version**
0.13.0

**Information about your GPU**
3060

**Additional context**
Running WSL2

Task Manager when I trigger Tabby code completion:
![image](https://github.com/TabbyML/tabby/assets/1381341/4fdfaf38-c2ce-411b-8835-e1a00fa9d836)
