### ISSUE TITLE
Logged out of Tabby Web after about 10 minutes even when active

### ISSUE THREAD

**Issue by ge-hall** [TabbyML/tabby#2557]
**Describe the bug**
When using tabby web features, particularly /playground. I am logged out after about 10 minutes. This occurs even when actively interacting in chat window. This has happened in v 0.11.0 to current. Older versions would keep unprocessed text from chat prompt and it would be in chat history on re-login. Version 0.12.0 and 0.13.0 lose entered text but retain processed chat.

**Information about your version**
Please provide output of `tabby --version`
tabby 0.13.0

**Information about your GPU**
Please provide output of `nvidia-smi`
Apple M1 Ultra

**Additional context**

- tabby installed and updated using brew.
- executed with command ``` tabby serve --port 8090 --device metal
- models configured using ~/.tabby/config.toml
```toml
[model.completion.http]
kind = "ollama/completion"
api_endpoint = "http://localhost:11434"
#model_name = "llama3"
#prompt_template = "<PRE> {prefix} <SUF>{suffix} <MID>"

#[model.completion.local]
#model_id = "DeepseekCoder-6.7B"

[model.chat.http]
kind = "ollama/chat"
model = "llama3"
api_endpoint = "http://localhost:11434"
# [model.chat.local]
# model_id = "Mistral-7B"
```
- message on start 
JWT secret is not set
Tabby server will generate a one-time (non-persisted JWT secret for current process.
Pleas set the TABBY_WEBSERVER_JWT_TOKEN_SECRET environment variable for production usage.

Replication steps.
1. interactive chat left for > 10 minutes then enter some new prompt.
<img width="1834" alt="Screenshot 2024-07-01 at 5 39 45 PM" src="https://github.com/TabbyML/tabby/assets/24502711/7cddb6f1-644e-4d71-90ef-fcfcb30c6788">
2. hit enter with response as login prompt, login
<img width="1660" alt="Screenshot 2024-07-01 at 5 39 57 PM" src="https://github.com/TabbyML/tabby/assets/24502711/c342db0f-7dee-4c5e-9590-fd4e40d328f3">
3. return to /playground after login and notice text in chat prompt is not in the history version of original chat.
<img width="1772" alt="Screenshot 2024-07-01 at 5 40 24 PM" src="https://github.com/TabbyML/tabby/assets/24502711/b18fc11c-452b-4c05-af3e-6becd471e0b8">
