### ISSUE TITLE
Problem with Ollama HTTP server config

### ISSUE THREAD

**Issue by SirMomster** [TabbyML/tabby#2616]
**Describe the bug**
I'm unable to get code completions when using tabby with Ollama as a HTTP completion. I use the following Ollama config in the config.toml for tabby:

```toml
[model.completion.http]
kind = "ollama/completion"
model_name = "codellama:7b"
api_endpoint = "http://ollama:9091"
prompt_template = "<PRE> {prefix} <SUF>{suffix} <MID>"
```

Ollama refers to my docker container running ollama, this connection seems to work fine yet everytime I try in vscode I get the following log entry in Ollama: 

```log
    time=2024-07-10T19:04:24.178Zlevel=WARNsource=types.go:406msg=invalid option providedoption=

[GIN] 2024/07/10 - 19:04:24 | 200 |  357.972945ms |      172.29.0.4 | POST     "/api/generate"
```

I expect that something goes wrong during the request from tabby to Ollama.

**Information about your version**
tabby version is 0.13.1

**Information about your GPU**
All good as this is managed by Ollama and works fine for other models.

**Additional context**
I run an Ollama server in docker which works fine for other models and TabbyML also in docker. I connect using the config.toml as described above.

---

Many thanks in advance.

**Comment by wsxiaoys** [comment]
Hi - could you also share the log information from tabby side? If helpful, maybe turn on `RUST_LOG=debug` environment variable to generate more detailed log for debugging purpose.

**Comment by SirMomster** [comment]
@wsxiaoys I did some further investigation, and it just seems that the model wasn't performing as expected. When it returns no response, we, of course, see no results in VS Code. Sorry for bothering you with this.

FYI, for anyone also getting this problem and seeing the logs in Ollama:  
```
time=2024-07-10T19:04:24.178Zlevel=WARNsource=types.go:406msg=invalid option providedoption=
```

It doesn't hinder tabby nor ollama from generating results (in my case).

Do you have more examples of models and prompt_templates like the one in the docs for codellama?

```toml
model_name = "codellama:7b"
prompt_template = "<PRE> {prefix} <SUF>{suffix} <MID>"
```

Or could you maybe point me towards some information on how these prompt_templates are made? So I can test some other models to see if they yield better results? Or if I should open another issue or contact support elsewhere, feel free to close this issue.

**Comment by wsxiaoys** [comment]
The prompt template is tied to the way the model is trained; therefore, it can be obtained from the model card or the source code published by the author. In the case of CodeLlama, it is available at https://github.com/meta-llama/codellama/blob/e81b597e44dbecc2a0dedb9949fdf84adfc22395/llama/generation.py#L488

**Comment by benmkw** [comment]
I might have a similar issue, I installed ollama using their native mac installer (ollama version is 0.2.7) and used it with other programs/ can chat with models in the terminal.

When I configure it for tabby (v1.8.0 (pre-release)) I can not get it to connect though.

In the logs I get `"Health check request: GET http://localhost:11434/v1/health` where a health enpoint seemingly does not exist for ollama (https://github.com/ollama/ollama/issues/1378) and for completions tabby calls `"Completion request: POST http://localhost:11434/v1/completions` but it should be more like `http://localhost:11434/v1/chat/completions` (which works when invoked with curl).

This is my config:

```toml
[model.completion.http]
kind = "openai/completion"
model_name = "codellama:7b"
api_endpoint = "http://localhost:11434"
api_key = "ollama"
```

Since other are clearly using it I'm probably holding it wrong in some way but I just did not yet uncover the issue.
