### ISSUE TITLE
tabby-cpu docker wont work

### ISSUE THREAD

**Issue by b-reich** [TabbyML/tabby#2634]
```yaml
services:
  tabby:
    restart: always
    image: tabbyml/tabby
    entrypoint: /opt/tabby/bin/tabby-cpu
    command: serve --model StarCoder-1B --chat-model Qwen2-1.5B-Instruct
    volumes:
      - ".data/tabby:/data"
    ports:
      - 8080:8080
```
which is document here https://tabby.tabbyml.com/docs/quick-start/installation/docker-compose/ wont work

```
tabby-1  | 2024-07-13T12:53:36.624504Z  WARN llama_cpp_server::supervisor: crates/llama-cpp-server/src/supervisor.rs:99: llama-server <embedding> exited with status code 127
tabby-1  | 2024-07-13T12:53:36.624528Z  WARN llama_cpp_server::supervisor: crates/llama-cpp-server/src/supervisor.rs:111: <embedding>: /opt/tabby/bin/llama-server: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
```

_Originally posted by @b-reich in https://github.com/TabbyML/tabby/issues/2082#issuecomment-2226889985_

**Comment by wsxiaoys** [comment]
Hi, thanks for reporting the issue. For a workaround, I recommend use the linux binary distribution directly: https://tabby.tabbyml.com/docs/quick-start/installation/linux/#download-the-release

**Comment by kannae97** [comment]
I also encountered the same error😭

**Comment by 0x4139** [comment]
The issue seems to be related to the llama-server, cublas should be statically linked when building the binary if interested in can submit a pull request

**Comment by 5bug** [comment]
I also encountered the same error😭
Thank you very much for your hard work in fixing it.

**Comment by 0x4139** [comment]
Submitted the pull request #2711 . In the meanwhile you can use my temporary image `0x4139/tabby-cuda`

If you're using docker compose you can use the following snippet:

```yaml title="docker-compose.yml"
version: '3.8'

services:
  tabby:
    restart: always
    image: 0x4139/tabby-cuda
    command: serve --model StarCoder-1B --chat-model Qwen2-1.5B-Instruct --device cuda
    volumes:
      - "$HOME/.tabby:/data"
    ports:
      - 8080:8080
    environment:
      - PATH=/usr/local/cuda/bin:$PATH
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/compat:$LD_LIBRARY_PATH
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

If you're using docker you can use the following snippet:

  ```bash title="run.sh"
  docker run -it --gpus all \
    -p 8080:8080 \
    -v $HOME/.tabby:/data \
    -e PATH=/usr/local/cuda/bin:$PATH \
    -e LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/compat:$LD_LIBRARY_PATH \
    tabbyml/tabby serve --model StarCoder-1B --chat-model Qwen2-1.5B-Instruct --device cuda
  ```

@b-reich @kannae97  This should solve your issue.
