### ISSUE TITLE
Codestral API Integration not working

### ISSUE THREAD

**Issue by anitsch-scs** [TabbyML/tabby#2788]
**Describe the bug**
Completion with Codestral via HTTP API does not work.

Not with
config.toml
```
[model.completion.http]
kind = "mistral/completion"
api_endpoint = "https://api.mistral.ai"
api_key = "<my_key>"
```
nor with config.toml
```
[model.completion.http]
kind = "mistral/completion"
api_endpoint = "https://codestral.mistral.ai/v1/fim/completions"
api_key = "<my_key>"
```

My docker-compose.yml:
```
services:
  tabby:
    container_name: tabby
    image: tabbyml/tabby:latest
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
      - ./config.toml:/root/.tabby/config.toml
    command: serve
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
```

I can login in the webui and connect the Tabby Plugin in IntelliJ with tabby.

Symptoms:
- no suggestions, just spinning circle in IntelliJ
- no logs (except started-message) from tabby server

**Information about your version**
0.14.0
