### ISSUE TITLE
Requested int8_float16 compute type

### ISSUE THREAD

**Issue by yinjiahuidada** [TabbyML/tabby#289]
**Describe the bug**
When I start the docker with docker-compose.yml
```
version: '3.5'
services:
  tabby:
    # restart: always
    image: tabbyml/tabby
    command: serve --model TabbyML/SantaCoder-1B --device cuda
    volumes:
      - "/data/tabby:/data"
    ports:
      - 8080:8080
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
```

terminate called after throwing an instance of 'std::invalid_argument'
  what():  Requested int8_float16 compute type, but the target device or backend do not support efficient int8_float16 computation.

**Information about your GPU**
Please provide output of `nvidia-smi`
3b:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1)
5e:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1)
b1:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1)
d9:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1)

**Additional context**

**Comment by wsxiaoys** [comment]
Hi @yinjiahuidada,

Could you try passing the `--compute-type` argument to the start command? The available options can be found in the --help section.

**Comment by yinjiahuidada** [comment]
Hi @wsxiaoys 
I get the help, but it doesn't help me

When I use this config
```
version: '3.5'
services:
  tabby:
    # restart: always
    image: tabbyml/tabby
    command: serve --model TabbyML/SantaCoder-1B --device cuda --device-indices 0 --compute-type int8
    volumes:
      - "/data/tabby:/data"
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
Error
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Invalid compute type: cpu
```

When I use this config
```
"docker-compose.yml" 17L, 412C                                                                                                                                                                                                                                6,104         All
version: '3.5'
services:
  tabby:
    # restart: always
    image: tabbyml/tabby
    command: serve --model TabbyML/SantaCoder-1B --device cuda --device-indices 0 --compute-type float16
    volumes:
      - "/data/tabby:/data"
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
Error
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
```
It seems like my GPU does not support FP16 execution?
