### ISSUE TITLE
DeepSeek-Coder-V2-Lite stuck

### ISSUE THREAD

**Issue by m0wer** [TabbyML/tabby#3212]
**Describe the bug**
DeepSeek-Coder-V2-Lite is stuck at starting.

The web server does not even satrt after 10,000 s of “Starting“. Other models work fine. If within the container I kill the llama-server process and start it manually without --disable-log, it can work and the web server starts and provides completions.

If I then kill the manually started ollama-server process, the default one is able to spawn and be loaded to VRAM but it just doesn't reply to requests.

**Information about your version**

Happens with 0.16.1, 0.17.0 and 0.18.0-rc4.

**Information about your GPU**

NVIDIA GeForce RTX 3090

**Additional context**

Running a fresh instance with docker compose:

```yaml
services:
  tabby:
    image: tabbyml/tabby:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 30G
        reservations:
          devices:
            - driver: nvidia
              #count: all
              device_ids: ['1']
              capabilities:
                - gpu
    labels:
      traefik.enable: true
      traefik.http.routers.tabby.rule: Host(`domain`)
      traefik.http.routers.tabby.entrypoints: websecure
      traefik.http.services.tabby.loadbalancer.server.port: 8080
    volumes:
      - /data/tabby/data/:/data
    command: ["serve", "--model", "DeepSeek-Coder-V2-Lite", "--device", "cuda"]
    environment:
      RUST_LOG: debug
```

There's nothing relevant in the logs, just request logs but no errors.
