### ISSUE TITLE
Cannot configure embedding model via config.toml

### ISSUE THREAD

**Issue by shochdoerfer** [TabbyML/tabby#3769]
**Describe the bug**

My `config.toml` file looks like this:
```toml
[model.completion.http]
kind = "openai/completion"
model_name = "meta-llama/Meta-Llama-3.1-405B-Instruct-FP8"
api_endpoint = "https://openai.inference.de-txl.ionos.com/v1/"
api_key = "..."

[model.chat.http]
kind = "openai/chat"
model_name = "meta-llama/Meta-Llama-3.1-405B-Instruct-FP8"
api_endpoint = "https://openai.inference.de-txl.ionos.com/v1"
api_key = "..."

[model.embedding.http]
kind = "openai/embedding"
model_name = "BAAI/bge-large-en-v1.5"
api_endpoint = "https://openai.inference.de-txl.ionos.com/v1"
api_key = "..."
```

I run the Tabby binary with this command:
```bash
./bin/tabby serve --model StarCoder-1B --chat-model Qwen2-1.5B-Instruct
```

In the output log I see the info `Overriding completion model from config.toml.` and `Overriding chat model from config.toml.`. I don't see any info that tells me that the embedding model is overwritten. Any judging by the performance, it isn't.

According to the [docs](https://tabby.tabbyml.com/docs/references/models-http-api/openai/), this should work. But maybe I am missing something.

**Information about your version**

Version 0.23.0

**Information about your GPU**

I use Tabby in CPU-only mode.
