### ISSUE TITLE
Add support for LM Studio server

### ISSUE THREAD

**Issue by radoslav11** [TabbyML/tabby#3780]
Recently [LM Studio](https://lmstudio.ai) has become more popular, and it's probably one of the best options for local model running on a macbook in terms of GUI. However, the other neat feature is that it has server support making it a nice all in one gateway for local LLMs. In particular, it also supports MLX as runtime for inference. 

I have been using Tabby with vim through the builtin inference, but I would like to switch this to be through LM Studio. Tabby already supports [Ollama](https://tabby.tabbyml.com/docs/references/models-http-api/ollama/), so if it's not a huge ask could you add support for something similar for LM Studio? 

The LM Studio API's are [OpenAI compatible](https://lmstudio.ai/docs/api/endpoints/openai), so hopefully this might end up being easy to setup.

**Comment by Sma1lboy** [comment]
Hello @radoslav11, if you use LM Studio and OpenAI compatible APIs, I think you can directly access LM Studio as an endpoint by configuring your local config.toml; it seems that Tabby doesn't need to do any extra operations? I tried using LM Studio with `deepseek-r1-distill-qwen-7b` by configuring it in config.toml.

```toml
[model.chat.http]
kind = "openai/chat"
model_name = "deepseek-r1-distill-qwen-7b"
api_endpoint = "http://localhost:1234/v1"  #default port from LM studio
api_key = ""
```

It is feasible

<img width="1111" alt="Image" src="https://github.com/user-attachments/assets/feee833b-db98-4494-87dc-1a053b30d1bf" />

By the way, we are still planning how long it will take to add support for the think tag, and we will also add documentation related to LM Studio later. Thanks for sharing
