### ISSUE TITLE
Ollama http support for chat

### ISSUE THREAD

**Issue by WizardlyBump17** [TabbyML/tabby#3846]
**Please describe the feature you want**
We can already use Ollama for completion using http. It would be nice if we could also use it for chat.

**Additional context**
For completion, we can configure Tabby like this:
```toml
[model.completion.http]
kind = "ollama/completion"
api_endpoint = "http://127.0.0.1:11434"
model_name = "qwen2.5-coder:3b"
prompt_template = "<|fim_prefix|>{prefix}<|fim_suffix|>{suffix}<|fim_middle|>"
```

If we try to use the same idea, but for chat, like this:
```toml
[model.chat.http]
kind = "ollama/chat"
api_endpoint = "http://127.0.0.1:11434"
model_name = "qwen2.5:3b"
```
we get an error saying it is not supported: 
```
The application panicked (crashed).
Message:  Unsupported model kind: ollama/chat
Location: /root/workspace/crates/http-api-bindings/src/chat/mod.rs:50
```

We can confirm that at the said file: [crates/http-api-bindings/src/chat/mod.rs](https://github.com/TabbyML/tabby/blob/6f838d87f77f99ee865b0755a042818c91491c68/crates/http-api-bindings/src/chat/mod.rs).

After some research, I found out that this feature was already added at some point in the past (1d1edfec6ebc09526399abee428f9406efd31b87), but got removed after one month (64cc7f493f6e0e551e24892347c65d58508917d6).

It would be really nice to be able to use only one service for the completion, chat and embedding.

---
Please reply with a 👍 if you want this feature.
