### ISSUE TITLE
A very long start server

### ISSUE THREAD

**Issue by sh1man** [TabbyML/tabby#4027]
I waited 40 minutes for the launch. After rebooting, the same thing happens

**Describe the bug**
log file
Writing to new file.
✅ Checksum OK.

⠋     0.000 s	Starting...
⠙     0.080 s	Starting...
⠹     0.161 s	Starting...
⠸     0.241 s	Starting...
....
https://pastebin.com/
```
services:
  tabby:
    image: tabbyml/tabby
    container_name: tabby
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${HOME}/.tabby:/data
    environment:
      - TABBY_DISABLE_USAGE_COLLECTION=1
    command: serve --model Qwen2.5-Coder-3B --device cuda --chat-model Qwen2-1.5B-Instruct
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


```
**Information about your version**
tabby version 

**Information about your GPU**

NVIDIA-SMI 550.120                Driver Version: 550.120        CUDA Version: 12.4

**Additional context**
