### ISSUE TITLE
Slower autocomplete after update v0.28.0 (self-hosting)

### ISSUE THREAD

**Issue by malvavisc0** [TabbyML/tabby#4208]
After latest update I've been restarting the service from time to time because the autocomplete become unresponsive or very slow to respond. This didn't happen before and I haven't changed anything on my server.

Hard to explain.

**Comment by zwpaper** [comment]
Hi @malvavisc0, can you share more informations like:
1. which version did you run before v0.28.0? 
2. what is your models running tabby?
3. what is your system?
4. is vscode plugin version changed?

Was there any indication of an impending slowdown, such as standard output logs, plugin debug logs, following intensive usage, or after a period of inactivity?

**Comment by malvavisc0** [comment]
1.- I've been using Tabby for around for around 7 to 8 months with no problems at all until recently. I've been installing update after update as soon as I receive a notification in VS Code, and using watchtower for Docker. In docker I use: `image: tabbyml/tabby`, should I try `docker pull ghcr.io/tabbyml/tabby:latest`?

2.- This is my config:
```toml
[model.completion.local]
model_id = "DeepSeekCoder-6.7B"

[model.chat.local]
model_id = "Qwen2.5-Coder-14B-Instruct"

[model.embedding.local]
model_id = "Nomic-Embed-Text"

[anonymousUsageTracking]
disable = false

[logs]
level = "debug"
```

3.- I'm using 2 RTX 3090

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/b8adeb16-db79-4e28-a03e-e10303669170" />

Should I try to fit everything is just one GPU?

4-. I'm using v1.28.0 of the plugin in VSCode. (Version of Code: 1.99.3)

99% of the time I'm using Python, it Tabby takes a lot to start, around 15 minutes, but after that it was just working great. Now, I'm seeing a bunch of `Health check request failed`, while the circle animation never ends.
