### ISSUE TITLE
Improve tabbyML's performance on my personal project

### ISSUE THREAD

**Issue by XunHang** [TabbyML/tabby#463]
**Please describe the feature you want**
I used tabbyML plugin and was blown away by its beauty. Thank you very much for such a wonderful work.

At the same time, I hope it will provide suggestions for some of my personal projects.
I read some issues in the repo and found https://github.com/TabbyML/tabby/issues/354 and https://github.com/TabbyML/tabby/issues/91 that may be relevant, but I don't know how to do it. 

Do I just need to modify the config.toml in ~/.tabby like below:

``` toml
[[repositories]]
git_url = "https://github.com/TabbyML/tabby.git"

[projects]
[projects.main_repo]
name = "main"
git_url = "https://github.com/xh/main_pro.git"
[projects.sub_repo]
name    = "sub_0"
git_url = "https://github.com/xh/sub_0_pro.git"
[projects.sub_repo]
name    = "sub_1"
git_url = "https://github.com/xh/sub_1_pro.git"
```
(PS: Sorry I need to write a fake url for privacy reasons.)

Maybe there is a document about this config.toml?

---
Please reply with a 👍 if you want this feature.
