### ISSUE TITLE
On RTX 2080, external display might got freeze during usage peak

### ISSUE THREAD

**Issue by newyorkthink** [TabbyML/tabby#522]
first i have three screen, one is laptop screen , two is typec screen, three is HDMI screen
```
Screen 0: minimum 8 x 8, current 3840 x 2160, maximum 32767 x 32767
eDP1 connected primary 1920x1080+1920+1080 (normal left inverted right x axis y axis) 340mm x 190mm
   3840x2160     60.00 +
   1920x1080     59.96  
   1920x1080_60.00  59.96* 
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
DP3 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
DVI-I-5-4 disconnected (normal left inverted right x axis y axis)
DVI-I-4-3 disconnected (normal left inverted right x axis y axis)
DVI-I-3-2 disconnected (normal left inverted right x axis y axis)
DVI-I-2-1 disconnected (normal left inverted right x axis y axis)
DP-1-0 disconnected (normal left inverted right x axis y axis)
DP-1-1 disconnected (normal left inverted right x axis y axis)
DP-1-2 disconnected (normal left inverted right x axis y axis)
HDMI-1-0 connected 1920x1080+0+1080 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  74.97    59.94    50.00  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
DP-1-3 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 609mm x 355mm
   3840x2160     59.98 +  59.94    50.00    29.97    25.00    23.98  
   2560x1440     59.95  
   1920x1080     60.00*   59.94  
   1600x900      60.00  
   1280x720      60.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
```

and GPU use
![image](https://github.com/TabbyML/tabby/assets/87791643/f36357e5-5ff2-49c0-99a5-6e5ebbdc1b6b)
i introduce this capture , GPU use 38% is about HDMI screen, because HDMI is direct to RTX GPU, and you can show the GPU men is 0.3G, is not run tabby, so this time, my laptop is normal

======

when I try run tabby :
![image](https://github.com/TabbyML/tabby/assets/87791643/54c72eec-9436-431e-b5a4-7f0d40672a0a)
it just run now, and compose is the following:
```
  tabby:
    image: tabbyml/tabby:latest
    hostname: tabby
    container_name: tabby
    runtime: nvidia
    volumes:
      - ./docker_data/tabby/data:/data
      - ./docker_data/tabby/models/StarCoder-1B:/models/StarCoder-1B
    ports:
      - "8080:8080"
    command: serve --model /models/StarCoder-1B --device cuda
```

![image](https://github.com/TabbyML/tabby/assets/87791643/fd5e16da-3af0-48b1-9532-1baca4477ea1)

not , you can see , tabby is run, the gpu is using

so, this time the laptop is normally running tabby.

=======

when I, open vscode, the extension is run
![image](https://github.com/TabbyML/tabby/assets/87791643/98c3f663-f556-48f4-ac22-0ecf58c51b54)
is normal to, 
and this time , the gpu info is normal too
![image](https://github.com/TabbyML/tabby/assets/87791643/1ca5b548-93a4-43d4-b56f-61f478550ece)

======

now , i use tabby to give me some suggestion
![image](https://github.com/TabbyML/tabby/assets/87791643/729cfb4b-c53d-4d3e-a37f-281478881163)

my two screen is freeze , cannot any move, just break.
and i show gpu info, the gpu is drop to zero
![image](https://github.com/TabbyML/tabby/assets/87791643/b5ae2d02-bde9-4f30-bf88-4f26d301c409)

i cannot to operate my two screen,is freeze

**Comment by newyorkthink** [comment]
i test, i exclusive the docker compose configure, when I use same tabby docs config is happen same bug, my screen is freeze again
```
  tabby:
    image: tabbyml/tabby:latest
    hostname: tabby
    container_name: tabby
    volumes:
      - ./docker_data/tabby/data:/data
      - ./docker_data/tabby/models/StarCoder-1B:/models/StarCoder-1B
    ports:
      - "8080:8080"
    command: serve --model /models/StarCoder-1B --device cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

**Comment by newyorkthink** [comment]
> Having the same issue as well, happen after a long time in IDLE mode it seems

how can you fixed its

**Comment by leamsigc** [comment]
For me so far I have not freeze here is my compose file 
```yml
version: '3.5'
services:
  tabby:
    # restart: always
    image: tabbyml/tabby:nightly
    # command: serve --model TabbyML/WizardCoder-3B --device cuda
    command: serve --model TabbyML/Mistral-7B --device cuda
    volumes:
      - "$HOME/.tabby:/data"
    ports:
      - 9898:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              options:
                memory_fraction: '0.8'
              count: 1
              capabilities: [gpu]



```

**Comment by newyorkthink** [comment]
> For me so far I have not freeze here is my compose file
> 
> ```yaml
> version: '3.5'
> services:
>   tabby:
>     # restart: always
>     image: tabbyml/tabby:nightly
>     # command: serve --model TabbyML/WizardCoder-3B --device cuda
>     command: serve --model TabbyML/Mistral-7B --device cuda
>     volumes:
>       - "$HOME/.tabby:/data"
>     ports:
>       - 9898:8080
>     deploy:
>       resources:
>         reservations:
>           devices:
>             - driver: nvidia
>               options:
>                 memory_fraction: '0.8'
>               count: 1
>               capabilities: [gpu]
> ```

i try use you config, is same freeze 

```
  tabby:
    image: tabbyml/tabby:latest
    hostname: tabby
    container_name: tabby
    volumes:
      - ./docker_data/tabby/data:/data
      - ./docker_data/tabby/models/StarCoder-1B:/models/StarCoder-1B
    ports:
      - "8080:8080"
    # command: serve --model /models/StarCoder-1B
    # runtime: nvidia
    command: serve --model /models/StarCoder-1B --device cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              options:
                memory_fraction: '0.8'
              count: 1
              capabilities: [gpu]

```

**Comment by leamsigc** [comment]
Can you try with a smaller model, for me now I got the same problem after a while, it seems like VRAM overload or something, that make the output crash, but is working correctly with no problems with the regular screen

**Comment by newyorkthink** [comment]
> Can you try with a smaller model, for me now I got the same problem after a while, it seems like VRAM overload or something, that make the output crash, but is working correctly with no problems with the regular screen

i try other, but it same situation

**Comment by wsxiaoys** [comment]
Thanks for reporting the issue!

Looks like the bug is introduced between v0.1.2 and v0.2.0, trying to locate a commit causing the issue.

**Comment by wsxiaoys** [comment]
Hi @newyorkthink and @leamsigc, could you please try using the Docker tag [0.2.2-rc.1](https://hub.docker.com/layers/tabbyml/tabby/0.2.2-rc.1/images/sha256-ef0944f82e04fde83e112998997c4ec0340d95f36fb2f6d54788ceb9f81caf7f?context=explore) to see if it resolves the issue for you?

**Comment by newyorkthink** [comment]
> Hi @newyorkthink and @leamsigc, could you please try using the Docker tag [0.2.2-rc.1](https://hub.docker.com/layers/tabbyml/tabby/0.2.2-rc.1/images/sha256-ef0944f82e04fde83e112998997c4ec0340d95f36fb2f6d54788ceb9f81caf7f?context=explore) to see if it resolves the issue for you?

hi, i, am test the 0.2.2-rc.1,  recently i my screen is freeze, so, i restart os, i am recently test new version
![image](https://github.com/TabbyML/tabby/assets/87791643/c340e175-bfaf-42dc-aba1-d99e4939ccc6)

docker-compose settings
```
  tabby:
    image: tabbyml/tabby:0.2.2-rc.1
    hostname: tabby
    container_name: tabby
    volumes:
      - ./docker_data/tabby/data:/data
      - ./docker_data/tabby/models/StarCoder-1B:/models/StarCoder-1B
    ports:
      - "8080:8080"
    # command: serve --model /models/StarCoder-1B
    # runtime: nvidia
    command: serve --model /models/StarCoder-1B --device cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

```

i tested 0.2.2-rc.1cannot fixed it
