### ISSUE TITLE
The generated python code contains redundancies "]"

### ISSUE THREAD

**Issue by willwu1984** [TabbyML/tabby#575]
**Describe the bug**
The generated python code has syntax errors and contains redundancies "]".
`# sort array by bubble sort`
<img width="710" alt="企业微信截图_f7995034-a623-4cef-936b-2884d56b7d6f" src="https://github.com/TabbyML/tabby/assets/3654753/df682fdd-e62a-453d-b661-53f7e88e7750">

**Information about GPU**
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
```

**Additional context**
`compose.yaml`:
```
version: '3.5'
services:
  tabby:
    restart: always
    image: tabbyml/tabby
    command: serve --model TabbyML/CodeLlama-13B --device cuda
    volumes:
      - "$HOME/.tabby:/data"
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
VS Code Version: 1.83.1
