### ISSUE TITLE
Configuration instructions misleading for config.toml [[repositories]]

### ISSUE THREAD

**Issue by pypeaday** [TabbyML/tabby#596]
**Describe the bug**
The configuration page gives the following example for indexing external repositories for Tabby context:

```toml
# Index `tabby` source code as additional context for code completion.
[[repositories]]
git_url = "https://github.com/TabbyML/tabby.git"
```

The issue is that for someone who doesn't know anything about TOML, the natural choice for adding a second repository would be to do this:

```toml
# Index `tabby` source code as additional context for code completion.
[[repositories]]
git_url = "https://github.com/TabbyML/tabby.git"
git_url = "another repo"
```

But this causes an error when the scheduler tries to parse the config. The correct way to give a list of repositories _I think_ would be this:

```toml
# Index `tabby` source code as additional context for code completion.
[[repositories]]
git_url = "https://github.com/TabbyML/tabby.git"
[[repositories]]
git_url = "another repo"
```

Because of that I think one relatively simple change might be to change the `repositories` key to `repository` and then the example would look like:

```toml
[[repository]]
git_url = "https://github.com/TabbyML/tabby.git"
[[repository]]
git_url = "another repo"
```
