### ISSUE TITLE
Out of Memory on 2x Titan XP

### ISSUE THREAD

**Issue by Nitschi** [TabbyML/tabby#648]
# The Error
When starting the tabby server with Code-Llama7B it fails with a Cuda out-of-memory error:
```
user@mymachine:~/tabby-ai-assistant$ docker-compose up -d && docker logs tabby --follow
Creating network "tabby-ai-assistant_default" with the default driver
Creating tabby ... done
2023-10-27T09:15:09.866543Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:143: Starting server, this might takes a few minutes...
terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDA failed with error out of memory
```

Looking at nvidia-smi while starting, the used memory climbs quickly before the OOM and the resulting crash.

# My Code
My docker-compose file:
```
version: "3.5"
services:
  tabby:
    container_name: tabby
    image: tabbyml/tabby:0.4.0
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    command: serve --model TabbyML/CodeLlama-7B --device cuda --device-indices 0 --device-indices 1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
```

# My machine
## GPU (nvidia-smi)
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX TITAN X     Off | 00000000:01:00.0 Off |                  N/A |
| 22%   38C    P8              14W / 250W |     13MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce GTX TITAN X     Off | 00000000:02:00.0 Off |                  N/A |
| 22%   37C    P8              13W / 250W |      6MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1593      G   /usr/lib/xorg/Xorg                           10MiB |
|    1   N/A  N/A      1593      G   /usr/lib/xorg/Xorg                            3MiB |
+---------------------------------------------------------------------------------------+
```

OS: Ubuntu 20.04
CPU: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
