### ISSUE TITLE
Improve Timeout on Client Agent with CPU configuration

### ISSUE THREAD

**Issue by jhwgh1968** [TabbyML/tabby#689]
I feel like this is a bug, technically speaking? But as noted in other issues, there is not much support for CPU configuration anymore. This is especially since the removal of the < 1B parameter models. So it is probably an enhancement.

While I have gotten everything working, my issue is that the agent has a hard-coded 4 seconds expectation for the average response time. After 3 requests, considers the server unhealthy and then locks out further completions:

https://github.com/TabbyML/tabby/blob/90e446bfbaef76aedd43d46e74c0ba8a92109acb/clients/tabby-agent/src/CompletionProviderStats.ts#L187

I think this makes sense for most cases, but I personally would not mind having a longer timeout. The code it generates for me is worth it.

Currently I have to hack the source code to achieve this. Would it be possible to add this to the agent configuration? Such as:

```toml
## You can set the timeout for completion requests.
[completion.timeout]
auto = 5000 # ms, for auto completion when typing
manually = 30000 # ms, for manually triggered completion
healthy_limit = 4000 # ms <-- new
```

---
Please reply with a 👍 if you want this feature.
