### ISSUE TITLE
Playground api doesn't work locally

### ISSUE THREAD

**Issue by arcutright** [TabbyML/tabby#896]
**Describe the bug**
Trying to use `localhost:8080/playground` which sends calls to `localhost:8080/v1beta/chat/completions` which returns 501 not implemented.

Seems like this is intentional?

https://github.com/TabbyML/tabby/blob/39962c79ca1ebed0684ee443e46aae7cd4c78dfb/crates/tabby/src/serve.rs#L213-L218

**Information about your version**
using docker image 
```
tabbyml/tabby:nightly
Digest:sha256:8b37c64a2fdb56b3aa792ddc745c8490590fe15d32172d37bdd192754233b8ec
```

**Comment by wsxiaoys** [comment]
could you share the command starting tabby？

**Comment by arcutright** [comment]
sure, just using docker compose:

```sh
sudo docker compose up --force-recreate -d
```

and the following docker-compose.yml:

```yml
version: '3.5'

services:
  tabby:
    restart: always
    image: 'tabbyml/tabby:nightly'
    command: serve --model TabbyML/DeepseekCoder-1.3B
    volumes:
      - "$HOME/.tabby:/data"
    ports:
      - 8080:8080
```
