### ISSUE TITLE
Support for helix  

### ISSUE THREAD

**Issue by golovo** [TabbyML/tabby#944]
Could I use tabby with helix?
Thanks！

**Comment by wsxiaoys** [comment]
potential related to LSP protocol for tabby agent, cc @icycodes

**Comment by peterwilli** [comment]
Am late to the party, but it's easy now that Helix supports multiple LSP's per language:

<img width="1656" alt="Image" src="https://github.com/user-attachments/assets/4b63b4ff-9874-4567-8920-f1759b8f7487" />

This is my config, I do it using Rust, but you can also add other languages (just append the tabby language server to the `language-servers` array):

```toml
[[language]]
name = "rust"
auto-format = true
language-servers = [
    "rust-analyzer",
    "tabby-ml",
]

[language-server.rust-analyzer.config.checkOnSave]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
allFeatures = true
targetDir = "analyzer_target"

[language-server.tabby-ml]
command = "npx"
args = [
    "tabby-agent",
    "--lsp",
    "--stdio",
]
```

For more info on running Tabby as LSP: https://www.tabbyml.com/blog/create-tabby-extension-with-language-server-protocol
